### ISSUE TITLE
outdated url

### ISSUE THREAD

**Issue by ghost** [void-linux/void-installer#3]
Hi all!
My laptop has been running Void musl for nearly 2 years now without any breaks. Thx for that!
I'm most probably going to get my hands on a newer machine rather soon. So, out of curiosity, I've booted the minimal image to get The Feeling :-)
I was a bit surprised to see at the very beginning the installer still mentions voidlinux.eu instead of voidlinux.org 
Not that important to me, but maybe confusing for a new user.

Regards and keep-up with your awesome work on this amazing distro.

**Comment by the-maldridge** [comment]
Very outdated, especially since this installer hasn't ever been installed anywhere.  You should check the one on the mklive repo.
